config/routes.rb
Twitter::Application.routes.draw do

  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => 'pages#index'

  match 'signin' => 'sessions#new'
  match 'signout' => 'sessions#destroy'

  get "/pages/index"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor   :password
  attr_accessible :username, :email, :password, :password_confirmation, :name

  validates :username, :presence   => true,
                       :length     => { :maximum => 50 },
                       :uniqueness => { :case_sensitive => false }

  validates :email, :presence   => true,
                    :format     => { :with => /^[\w.+\-]+@[a-z\d.]+\.[a-z]+$/i },
                    :uniqueness => { :case_sensitive => false }

  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..12 }

  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  class << self
    def authenticate(username, submitted_password)
      user = find_by_username(username)
      (user && user.has_password?(submitted_password)) ? user : nil
    end

    def authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
  end

  private
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)  
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @title = 'Welcome'
    @user = User.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @title = "Sign in"
  end

  def create
    user = User.authenticate(params[:session][:username],
                             params[:session][:password])
    if user.nil?
      @title = "Sign in"
      flash.now[:error] = "Invalid email/password combination."
      render 'new'
    else
      sign_in user
      redirect_to user, :flash => {:success => "Welcome back!"}
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update]
  before_filter :correct_user, :only => [:edit, :update]

  def show
    @user = User.find(params[:id])
    @title = @user.username
  end

  def new
    @user = User.new
    @title = "Sign up"
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      redirect_to @user, :flash => { :success => "Welcome to the Twitter!" }
    else
      @title = "Sign up"
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    @title = "Edit profile"
  end

  def update
    @user = User.find(params[:id])
    @title = "Edit profile"
    if @user.update_attributes(params[:user])
      redirect_to @user, :flash => { :success => "Your profile has been updated." }
    else
      flash.now[:error] = "Please fill in all required fields."
      render 'edit'
    end
  end

  private
    def authenticate
      deny_access unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def title
    @title ? "Twitter | #{@title}" : 'Twitter'
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    current_user = nil
  end

  def deny_access
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end

  private
    
    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user, options = { :size => 95 })
    gravatar_image_tag(user.email.downcase, :alt => user.username,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/layouts/_header.html.erb
<header class="remove-bottom">
  <div class="four columns alpha">
    <h1><%= link_to 'Twitter', root_path %></h1>
  </div>
  <div class="eight columns omega right">
    <% if signed_in? %>
      <nav>
        <ul class="tabs right">
          <li><%= link_to "Profile", user_path(current_user) %></li>
          <li><%= link_to "Edit", edit_user_path(current_user) %></li>
          <li><%= link_to "Sign out", signout_path %></li>
        <ul>
      </nav>
    <% else %>
      <%= form_for(:session, :url => sessions_path) do |f| %>
        <%= f.text_field :username, :class => "inline", :placeholder => "username" %>
        <%= f.password_field :password, :class => "inline", :placeholder => "password" %>
        <%= f.submit :value => "Sign in", :class => "button inline" %>
      <% end %>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= render 'layouts/header' %>
  <hr />
  <% flash.each do |key, value| %>
    <div class="flash <%= key %> alert-message">
      <%= value %>
      <a class="close" href="#">×</a>
    </div>
  <% end %>
  <%= yield %>
</div>
<%= debug params if Rails.env.development? %>
</body>
<script>
  $(".alert-message").alert()
</script>
</html>

app/views/pages/index.html.erb
<section>
  <div class="eight columns alpha offset-by-one">
    <p>This is <a href="http://twitter.com">Twitter</a> clone app, made by <a href="http://twitter.com/indiche/">indiche</a>. Purpose of this app is to help me improve my <a href="http://rubyonrails.com">Ruby on Rails</a> skills.</p>
  </div>
  <div class="one columns omega offset-by-two">
    <%= render 'users/sign_up' %>
  </div>
</section>

app/views/users/_sign_up.html.erb
<h3>Sign up</h3>
<%= form_for @user do |f| %>
  <%= f.text_field :username, :placeholder => "username" %>
  <%= f.text_field :email, :placeholder => "email" %>
  <%= f.password_field :password, :placeholder => "password" %>
  <%= f.password_field :password_confirmation, :placeholder => "password confirmation" %>
  <%= f.submit :value => "Sign up" %>
<% end %>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <%= f.text_field :username, :placeholder => "username" %>
  <%= f.text_field :name, :placeholder => "full name" %>
  <%= f.text_field :email, :placeholder => "email" %>
  <%= f.password_field :password, :placeholder => "password" %>
  <%= f.password_field :password_confirmation, :placeholder => "password confirmation" %>
  <%= f.submit :value => "Edit" %>
<% end %>

app/views/users/new.html.erb
<%= render 'sign_up' %>

app/views/users/show.html.erb
<div class="twelve columns alpha">
  <div class="two columns alpha">
    <%= gravatar_for @user %>
  </div>
  <div class="six columns">
    <% if @user.name %>
      <h2><%= @user.name %></h2>
    <% end %>
    <div class="meta">
      <%= @user.username %>
    </div>
  </div>
</div>
<div class="two columns omega">
  <%= link_to user_path(@user), user_path(@user) %>
</div>